### ISSUE TITLE
Can't open series links after updating to V2.1.0 

### ISSUE THREAD

**Issue by Marcaay** [jmooremcc/plugin.program.super.favourites#4]
Hi, since i'm on 2.1.0 I can't open links to series anymore. Links to movies or addons are working fine, but not for series. Neither out of a SF folder, nor via a created SF folder as widget.

**Comment by jmooremcc** [comment]
I need to see a specific example that I can replicate. It would also be very helpful to see your log. Go into SF settings and turn debugging on and then go through the steps that demonstrate the problem. 

Thanks

**Comment by Marcaay** [comment]
Hi, please see the attached log. Hope this will help. Thank's for support.

[Kodi193_SF210_Log.rtf.zip](https://github.com/jmooremcc/plugin.program.super.favourites/files/7490772/Kodi193_SF210_Log.rtf.zip)

**Comment by Marcaay** [comment]
Does it help? Could you detect the root cause for the problem? If you have a new version, I can also test it.
Thank you

**Comment by kwetter** [comment]
Has this been addressed yet. I experience a similar issue to the one from @Marcaay. When I click e created link, nothing happens (links go to local video files or locations within other addons). There is another outcome when I start Super Favorites from within the Plugin section of addons. When I then click on my created favorites links it always goes to the Video>Files Location and nothing else happens.

**Comment by jmooremcc** [comment]
I've got a version almost ready to release that I hope will resolve the issue.

I would like for you to give me a list of the steps you followed that created the problem along with a debug log so that I can test the next version before I release it.

When creating a debug log, please remember to go into SF settings and enable debug mode. This will add information that will help me see what's going on during execution.

You will also have to make sure that Kodi is in debug mode as well.
In your advancedsettings.xml file make sure you have the following:
"\<loglevel>1\</loglevel>"

**Comment by jmooremcc** [comment]
I've released version 2.2.1.
Let me know if this version resolves your issue.

**Comment by Goldenfreddy0703** [comment]
Hey there, sorry its been a few days but to help reproduce this issue or bug, here are the steps.

1. Download the TMDB Helper Addon
2. Go into TMDB Helper Addon and go to TV Shows, then popular
3. Add a random tv show to super favorites
4. Once it's added, go to super favorites
5. Click the TV Show on where you saved it
6. Notice the bug where nothing happens when you click the tv show you saved.

This should help reproduce this issue in order to get more information, I would provide a log but i was doing testing yesterday on new builds. 

BTW: The Latest version still has this bug. 

Thank you

**Comment by jmooremcc** [comment]
> 
@Goldenfreddy0703 
Version 2.2.3 should resolve that issue.
I tested it with the WNBC addon doing exactly what you tried and it worked with no problem.
In fact, not only the addon itself but individual programs worked as well.

If for some reason you are still experiencing the problem, please provide a debug log (pastebin) for me to examine.
In order to create a debug log, make sure you go into SF settings and enable debugging. 
Also make sure Kodi is setup for producing a debug log.

**Comment by Goldenfreddy0703** [comment]
OK sure, i will in a little bit. I just tested it yesterday but it maybe on my end when downloading your latest branch.

Thank you

**Comment by Goldenfreddy0703** [comment]
Hey so i manage to redownload superfavorites and turn on debug mode so here is a log. 


[kodi.log](https://github.com/jmooremcc/plugin.program.super.favourites/files/8037043/kodi.log)

**Comment by drout69** [comment]
I have what I might think be the same issue, showing in a different way. The use case here is using Seren to insert show listings into  a Super Favorites folder structure. This allows me to have a categorized tree of shows, eg, Comedy, Action, Drama and such when I insert the various Super Favourite folders into Kodi favorites. So the user flow is to open Kodi favorites, open a category, which now passes you to Super Favorites and from there try to play a show - which should open the player window with Seren.

I eliminated skin problems by going back to plain vanilla kodi and this issue still persisted. I eliminated Seren by also using Seren to write a show listing straight to Kodi favorites, clicking that show (within the Kodi favorites window) will correctly launch the player with Seren.

I created some log snippets with these two use cases:  https://paste.kodi.tv/esogofamum.kodi

This is an Nvidia Shield running (unfortunately) the latest android update released for it and it has the latest Kodi 19.3 and freshly installed addons.

Some info:
skin.aeon.nox.silvo v8.0.1
script.skinshortcuts v2.0.1
plugin.video.seren v2.1.9
plugin.program.super.favourites v2.2.3

**Comment by drout69** [comment]
Actually, a correction to the statement above, where I say "should open a player window, it should actually be taking you to the seasons listings. The direct from Kodi favorites, does this correctly. Thanks!

**Comment by jmooremcc** [comment]
@drout69 
I'm not seeing the debug information I'm looking for.
Did you go into SF settings and enable debugging?
Also did you enable debug logging in Kodi?
I should be seeing something like this in the log:

> 2022-02-07 11:34:08.032 T:10496   DEBUG <general>: Super Favourites V2.1.0 : ------------------ Launch Parameters ------------------
2022-02-07 11:34:08.032 T:10496   DEBUG <general>: Super Favourites V2.1.0 : ?content_type=video
2022-02-07 11:34:08.032 T:10496   DEBUG <general>: Super Favourites V2.1.0 : ['plugin://plugin.program.super.favourites/', '7', '?content_type=video', 'resume:false']
2022-02-07 11:34:08.032 T:10496   DEBUG <general>: Super Favourites V2.1.0 : mode        = -2
2022-02-07 11:34:08.032 T:10496   DEBUG <general>: Super Favourites V2.1.0 : cmd         = None
2022-02-07 11:34:08.032 T:10496   DEBUG <general>: Super Favourites V2.1.0 : folder      = 
2022-02-07 11:34:08.032 T:10496   DEBUG <general>: Super Favourites V2.1.0 : params      = {'content_type': 'video'}
2022-02-07 11:34:08.032 T:10496   DEBUG <general>: Super Favourites V2.1.0 : launchMode  = video
2022-02-07 11:34:08.032 T:10496   DEBUG <general>: Super Favourites V2.1.0 : contentType = 
2022-02-07 11:34:08.032 T:10496   DEBUG <general>: Super Favourites V2.1.0 : viewType    = 0
2022-02-07 11:34:08.032 T:10496   DEBUG <general>: Super Favourites V2.1.0 : isHome      = False
2022-02-07 11:34:08.032 T:10496   DEBUG <general>: Super Favourites V2.1.0 : itemIndex   = -1
2022-02-07 11:34:08.032 T:10496   DEBUG <general>: Super Favourites V2.1.0 : ident       = 7
2022-02-07 11:34:08.033 T:10496   DEBUG <general>: Super Favourites V2.1.0 : -------------------------------------------------------
202

> 

Also have you upgraded to SF version 2.2.3?

**Comment by jmooremcc** [comment]
> 

@Goldenfreddy0703 
I'm not seeing the debug information in the log you submitted I was expecting.
I should be seeing something like this in the log:

> 2022-02-07 11:34:08.032 T:10496   DEBUG <general>: Super Favourites V2.1.0 : ------------------ Launch Parameters ------------------
2022-02-07 11:34:08.032 T:10496   DEBUG <general>: Super Favourites V2.1.0 : ?content_type=video
2022-02-07 11:34:08.032 T:10496   DEBUG <general>: Super Favourites V2.1.0 : ['plugin://plugin.program.super.favourites/', '7', '?content_type=video', 'resume:false']
2022-02-07 11:34:08.032 T:10496   DEBUG <general>: Super Favourites V2.1.0 : mode        = -2
2022-02-07 11:34:08.032 T:10496   DEBUG <general>: Super Favourites V2.1.0 : cmd         = None
2022-02-07 11:34:08.032 T:10496   DEBUG <general>: Super Favourites V2.1.0 : folder      = 
2022-02-07 11:34:08.032 T:10496   DEBUG <general>: Super Favourites V2.1.0 : params      = {'content_type': 'video'}
2022-02-07 11:34:08.032 T:10496   DEBUG <general>: Super Favourites V2.1.0 : launchMode  = video
2022-02-07 11:34:08.032 T:10496   DEBUG <general>: Super Favourites V2.1.0 : contentType = 
2022-02-07 11:34:08.032 T:10496   DEBUG <general>: Super Favourites V2.1.0 : viewType    = 0
2022-02-07 11:34:08.032 T:10496   DEBUG <general>: Super Favourites V2.1.0 : isHome      = False
2022-02-07 11:34:08.032 T:10496   DEBUG <general>: Super Favourites V2.1.0 : itemIndex   = -1
2022-02-07 11:34:08.032 T:10496   DEBUG <general>: Super Favourites V2.1.0 : ident       = 7
2022-02-07 11:34:08.033 T:10496   DEBUG <general>: Super Favourites V2.1.0 : -------------------------------------------------------
202

> 
Please make sure that you enabled SF debugging in SF settings.
Also FYI, your weather addon is throwing an exception.

Thanks

**Comment by Marcaay** [comment]
Hi jmooremcc,

I created a log today with kodi loglevel=1 + sf debug mode  and snapped it from trying to starting a link to a series „Kesslers Knigge“.
I don’t know why, but can’t upload it to pastebin. I attached it to this mail and hope this is good for you to see what’s happening.

My use case:
- I created SuperFavourite folders to organize series, movies, addons, etc.
- I linked a series „Kesslers Knigge“ from xStream addon to the „Serien Watchlist“ SF folder
- If I try to start the „Kesslers Knigge“ for example, kodi will show 2 times a loading screen and nothing happens
- If I go into the xStream addon and click on the series link „Kesslers Knigge“ it is working fine
- info: I faced the problem only with series links. With movie links (also from xStream addon) I don*t have this problem

Thank you for your efforts. Your addon is a big part of my own kodi build and responsible for some watchlist and kodi menus.

Regards, 
Marcaay

**Comment by jmooremcc** [comment]
> 
@Marcaay 

Here's the test I performed:
I have the "WNBC Programs" addon loaded in Kodi.
I clicked on that addon and scrolled down to "Brooklyn Nine-Nine".
I then right clicked on the "Brooklyn Nine-Nine" folder and selected add to SF.
Next I selected the "TV Shows" folder I already had as the destination.

I then opened SF and scrolled down to the "TV Shows" folder and then clicked the "Brooklyn Nine-Nine" folder.
SF opened the "Brooklyn Nine-Nine"  folder to reveal a list of programs.
I then clicked on one of the programs and it played.

Is this the same procedure you followed?
Once I'm able to see your log, I'll be able to dig a little deeper.

John

**Comment by Marcaay** [comment]
Hi John,

Yes, I can confirm, I’m able to reproduce your described scenario and it worked also for me with the WNBC Programs addon „Brooklyn Nine-Nine“.
Could you please try to do it in the same way but with the following scenario:

Addon: ARDundZDF

Please navigate to the following menu:
ARDundZDF -> ZDF Mediathek -> ZDF-sportstudio -> Bundesliga

Then right click on „Bundesliga“ and add this to a SF folder. Then go to the SF folder and try to start the „Bundesliga“ favorite

Did you see my attached log, because you wrote „Once I’m able to see your log…“?

Thanks
Marc

**Comment by drout69** [comment]
Sorry guys, thought I had debug on. My error. Anyway, here's a log from activating Kodi and doing the two flows described above.
1. Kodi Favorites -> SuperFavoutites (->) Seren Season Listings (broken window focus)
2. Kodi Favorites -> Seren Season Listings  (succesful)

https://paste.kodi.tv/alizatiwih.kodi

Thanks very much for digging in.

**Comment by jmooremcc** [comment]
@drout69 @Goldenfreddy0703 @Marcaay 

I've just uploaded SF Version 2.2.4
Marc, I tested this version with the addon you wanted me to look at and it appears to work.
I could only do a limited amount of testing since the path you wanted me to test would not play on my system when I directly ran the addon. However, I found other files that would play and tested access to them in SF.

Please let me know how this version performs on your systems.

Thanks

John

**Comment by drout69** [comment]
Thanks John,
I will test it out in a couple of hours. Was there any change that requires me to re-write the favorites.xml files? ie. recreate my listings, due to the bug being in the meta-data that was written in the "Save to SuperFavorites" operation.

I want to make sure I'm giving it a valid test.

Thanks,

David

**Comment by drout69** [comment]
Big thumbs up from me. v2.2.4 fixes the Seren season listing issue I posted. Thanks very much John. I held back from Kodi 19 for so long due to SF being buggy. You're a champ!!!

-David

**Comment by Marcaay** [comment]
Hi John, the problem I mentioned with the ARDundZDF addon is solved. This is now working fine, thank you very much.
Only still the series links to e.g. xStream addon is still not working. In <2.2.4 it was loading two times after clicking on a link within a SF folder, now it is loading once and then showing the standard library screen I guess.


Am 12. Feb. 2022, 22:22, um 22:22, jmooremcc ***@***.***> schrieb:
***@***.*** @Goldenfreddy0703 @Marcaay
>
>I've just uploaded SF Version 2.2.4
>Marc, I tested this version with the addon you wanted me to look at and
>it appears to work.
>I could only do a limited amount of testing since the path you wanted
>me to test would not play on my system when I directly ran the addon.
>However, I found other files that would play and tested access to them
>in SF.
>
>Please let me know how this version performs on your systems.
>
>Thanks
>
>John
>
>--
>Reply to this email directly or view it on GitHub:
>https://github.com/jmooremcc/plugin.program.super.favourites/issues/4#issuecomment-1037490213
>You are receiving this because you were mentioned.
>
>Message ID:
***@***.***>

**Comment by jmooremcc** [comment]
> Hi John, the problem I mentioned with the ARDundZDF addon is solved. This is now working fine, thank you very much. Only still the series links to e.g. xStream addon is still not working. In <2.2.4 it was loading two times after clicking on a link within a SF folder, now it is loading once and then showing the standard library screen I guess. Am 12. Feb. 2022, 22:22, um 22:22, jmooremcc ***@***.***> schrieb: ***@***.*** @Goldenfreddy0703 @Marcaay
> I've just uploaded SF Version 2.2.4 Marc, I tested this version with the addon you wanted me to look at and it appears to work. I could only do a limited amount of testing since the path you wanted me to test would not play on my system when I directly ran the addon. However, I found other files that would play and tested access to them in SF. Please let me know how this version performs on your systems. Thanks John -- Reply to this email directly or view it on GitHub: [#4 (comment)](https://github.com/jmooremcc/plugin.program.super.favourites/issues/4#issuecomment-1037490213) You are receiving this because you were mentioned. Message ID:
> ***@***.***>

@Marcaay 
I've applied a fix that should fix all future issues of this type in SF Version 2.2.5
I've tested it with the xStream addon and it appears to be working now.
Please let me know if this has resolved the issue for.

Thanks

John

**Comment by neires** [comment]
@jmooremcc 

I can confirm that with the last change everything works normally again.
Both with xstream and with xship.
The episode lists are now opened normally again.
Thanks for the fix!

**Comment by Marcaay** [comment]
Hi John,

Thanks for your effort. Now, it seems to be fixed. I tested with few links and it was working fine.

Good work to keep this necessary addon alive!

Marc



Am 14. Feb. 2022, 17:37, um 17:37, jmooremcc ***@***.***> schrieb:
>> Hi John, the problem I mentioned with the ARDundZDF addon is solved.
>This is now working fine, thank you very much. Only still the series
>links to e.g. xStream addon is still not working. In <2.2.4 it was
>loading two times after clicking on a link within a SF folder, now it
>is loading once and then showing the standard library screen I guess.
>Am 12. Feb. 2022, 22:22, um 22:22, jmooremcc ***@***.***> schrieb:
>***@***.*** @Goldenfreddy0703 @Marcaay
>> I've just uploaded SF Version 2.2.4 Marc, I tested this version with
>the addon you wanted me to look at and it appears to work. I could only
>do a limited amount of testing since the path you wanted me to test
>would not play on my system when I directly ran the addon. However, I
>found other files that would play and tested access to them in SF.
>Please let me know how this version performs on your systems. Thanks
>John -- Reply to this email directly or view it on GitHub: [#4
>(comment)](https://github.com/jmooremcc/plugin.program.super.favourites/issues/4#issuecomment-1037490213)
>You are receiving this because you were mentioned. Message ID:
>> ***@***.***>
>
***@***.***
>I've applied a fix that should fix all future issues of this type in SF
>Version 2.2.5
>I've tested it with the xStream addon and it appears to be working now.
>Please let me know if this has resolved the issue for.
>
>Thanks
>
>John
>
>--
>Reply to this email directly or view it on GitHub:
>https://github.com/jmooremcc/plugin.program.super.favourites/issues/4#issuecomment-1039300511
>You are receiving this because you were mentioned.
>
>Message ID:
***@***.***>

**Comment by jmooremcc** [comment]
Thanks to everyone for your feedback.
